# Generated by Django 2.1.2 on 2018-10-22 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkData',
        ),
    ]
