# Generated by Django 2.1.2 on 2018-10-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0002_delete_workdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=32, verbose_name='公司名称')),
                ('products', models.CharField(max_length=32, verbose_name='主要产品')),
                ('work_place', models.CharField(max_length=32, verbose_name='工作地点')),
                ('salary', models.CharField(max_length=32, null=True, verbose_name='薪资')),
                ('preaching_time', models.CharField(max_length=32, verbose_name='宣讲时间')),
                ('preaching_place', models.CharField(max_length=32, verbose_name='宣讲地点')),
                ('preaching', models.CharField(max_length=32, verbose_name='宣讲')),
                ('delivery', models.CharField(max_length=32, verbose_name='投递')),
                ('delivery_time', models.CharField(max_length=32, verbose_name='投递时间')),
                ('position_1', models.CharField(max_length=32, verbose_name='职位1')),
                ('position_2', models.CharField(max_length=32, verbose_name='职位2')),
                ('assessment', models.CharField(max_length=32, verbose_name='测评')),
                ('examination', models.CharField(max_length=32, verbose_name='笔试')),
                ('interview', models.CharField(max_length=32, verbose_name='面试')),
                ('status', models.CharField(max_length=32, verbose_name='状态')),
                ('notes', models.CharField(max_length=32, null=True, verbose_name='备注')),
                ('preaching_information_link', models.CharField(max_length=32, null=True, verbose_name='宣讲信息')),
                ('delivery_link', models.CharField(max_length=32, null=True, verbose_name='网申链接')),
            ],
        ),
    ]
