# Generated by Django 2.1.2 on 2018-10-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_workdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32, verbose_name='状态')),
            ],
        ),
        migrations.RemoveField(
            model_name='workdata',
            name='status',
        ),
    ]
