# Generated by Django 2.1.2 on 2018-10-24 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20181024_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdata',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.Status'),
            preserve_default=False,
        ),
    ]
