# Generated by Django 2.1.4 on 2020-02-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vod_id', models.CharField(max_length=8, unique=True)),
                ('vod_cid', models.CharField(max_length=4)),
                ('vod_name', models.CharField(max_length=16)),
                ('vod_type', models.CharField(max_length=32)),
                ('vod_keywords', models.CharField(max_length=32)),
                ('vod_actor', models.CharField(max_length=32)),
                ('vod_director', models.CharField(max_length=32)),
                ('vod_content', models.TextField()),
                ('vod_pic', models.CharField(max_length=128)),
                ('vod_area', models.CharField(max_length=16)),
                ('vod_language', models.CharField(max_length=16)),
                ('vod_year', models.CharField(max_length=4)),
                ('vod_addtime', models.CharField(max_length=32)),
                ('vod_url', models.TextField()),
                ('vod_reurl', models.CharField(max_length=128)),
                ('vod_continu', models.CharField(max_length=32)),
                ('vod_status', models.IntegerField()),
                ('vod_isend', models.IntegerField()),
                ('list_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='VideoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vod_cid', models.IntegerField(unique=True)),
                ('list_name', models.CharField(max_length=16)),
            ],
        ),
    ]
