# Generated by Django 2.1.4 on 2020-02-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videodata',
            old_name='vod_isend',
            new_name='vod_length',
        ),
        migrations.RemoveField(
            model_name='videodata',
            name='vod_keywords',
        ),
        migrations.RemoveField(
            model_name='videodata',
            name='vod_reurl',
        ),
        migrations.RemoveField(
            model_name='videodata',
            name='vod_status',
        ),
        migrations.RemoveField(
            model_name='videodata',
            name='vod_type',
        ),
        migrations.AddField(
            model_name='videodata',
            name='vod_alias',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
