# Generated by Django 2.1.4 on 2020-02-05 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20200204_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vod_id', models.CharField(max_length=8, unique=True)),
                ('vod_name', models.CharField(max_length=16)),
                ('list_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='videodata',
            name='vod_cid',
        ),
        migrations.AddField(
            model_name='videodata',
            name='video_list',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='video.VideoList', to_field='vod_cid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videodata',
            name='list_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='videolist',
            name='vod_cid',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
