# Generated by Django 2.1.4 on 2020-02-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20200205_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videolist',
            old_name='vod_cid',
            new_name='list_id',
        ),
    ]
