# Generated by Django 2.1.4 on 2020-02-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20200205_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodata',
            name='video_list',
        ),
        migrations.AddField(
            model_name='videodata',
            name='vod_cid',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VideoList',
        ),
    ]
