# Generated by Django 2.1.4 on 2020-02-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20200205_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlist',
            name='is_add',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
