# Generated by Django 2.1.4 on 2020-02-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_requestlist_is_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='ctime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
