# Generated by Django 3.0.3 on 2020-02-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20200215_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='vod_url2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
