# Generated by Django 3.0.3 on 2020-02-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_videodata_vod_url2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='vod_url2',
            field=models.TextField(null=True),
        ),
    ]
