# Generated by Django 3.0.3 on 2020-02-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_auto_20200216_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='vod_alias',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
