# Generated by Django 3.0.3 on 2020-02-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_auto_20200229_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='vod_url',
            field=models.TextField(null=True),
        ),
    ]
