# Generated by Django 3.0.5 on 2020-04-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0013_auto_20200229_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vod_name', models.CharField(max_length=16)),
                ('vod_pic', models.CharField(max_length=32)),
                ('vod_url', models.CharField(max_length=32)),
                ('vod_index', models.IntegerField()),
            ],
        ),
    ]
