# Generated by Django 3.0.3 on 2020-05-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_carousellist'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='vod_douban_id',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='videodata',
            name='vod_rating',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
